export type taskList = [
    {
        id: string,
        player_id: string,
        tasks: string[],
        autogenerated: boolean,
        title: string,
        published: string
    },
]

export type task = [
    {
        id: string,
        theme_id: string,
        answer_type: number,
        description: string,
        answer: null,
        difficulty: number,
        position: number,
        is_solved: boolean,
        attempts: 1,
        "attempts_remains": 1
    },
]
