<script lang="ts">
  import { goto } from '@sapper/app.mjs'
  import Complexity from '../mocks/_complexity'
  import { joinCssClasses } from '../utils/utils'
  import { onMount } from 'svelte'
  import Id from '../services/randomUID.ts'
  import type { task } from '../types/tasks.type'
  import { fade } from 'svelte/transition'

  let themeData = []
  let tasksData = []
  let active: boolean = false

  let autoGenerated: boolean = true
  let id: string = Id()
  let theme: string = ''
  let difficulty = 0
  let position: number = 0
  let description: string = ''
  let image: string = ''
  // let answerOptions = [];
  // let taskHint = '';
  let answer = ''
  // let solution = '';

  $: disabled = !theme && !description && !answer

  const createTask = (id: string, theme: string, description: string, image: string, difficulty: number, position: number, answer: string): task => {
    return {
      id: id,
      theme_id: theme,
      answer_type: 0,
      description: description,
      answer: autoGenerated ? answer : null,
      image: image ? image : null,
      difficulty: difficulty,
      position: position,
      is_solved: false,
      attempts: 0,
      attempts_remains: 2
    }
  }

  const submitHandler = () => {
    if (tasksData) {
      localStorage.setItem('task', JSON.stringify([...tasksData, createTask(id, theme, description, image, difficulty, position, answer)]))
    } else {
      localStorage.setItem('task', JSON.stringify([createTask(id, theme, description, image, difficulty, position, answer)]))
    }
    goto('/tasks')
  }

  // let fields = [{ id: '1' }, { id: '2' }];
  // const handleClick = () => {
  //   fields = [...fields, { id: id }];
  // };

  onMount(() => {
    themeData = JSON.parse(localStorage.getItem('theme'))
    tasksData = JSON.parse(localStorage.getItem('task'))
  })
</script>

<svelte:head>
  <title>Add tasks</title>
</svelte:head>

<form class="form-horizontal" enctype="multipart/form-data" on:submit|preventDefault="{submitHandler}">
  <fieldset class="fieldset mr-2">
    <!-- checkbox Basic -->
    <div class="field mb-5"><label class="checkbox"> <input type="checkbox" bind:checked="{autoGenerated}" /> Auto generated </label></div>

    <!-- Select Basic -->
    <div class="field is-horizontal">
      <div class="field">
        <label class="label" for="topic">Select theme</label>
        <div class="control">
          <div class="select">
            <select id="topic" name="topic" bind:value="{theme}" required>
              {#if themeData}
                <option selected disabled></option>
                {#each themeData as theme (theme.id)}
                  <option value="{theme.id}">{theme.theme}</option>
                {/each}
              {:else}
                <option disabled>add theme</option>
              {/if}
            </select>
          </div>
          {#if !active}<button class="button is-primary" on:click|preventDefault="{() => (active = !active)}">Add theme</button>{/if}
        </div>
      </div>

      <div class="{joinCssClasses('field', !active ? 'is-invisible' : '')}">
        <label class="label" for="addTopic">Add theme</label>
        <div class="field has-addons">
          <div class="control">
            <input id="addTopic" name="answerOptions" class="input " placeholder="placeholder" type="text" bind:value="{theme}" />
          </div>
          <div class="control">
            <div
              class="button is-success"
              on:click|preventDefault="{() => {
                localStorage.setItem('theme', JSON.stringify(themeData === null ? [{ id: id, theme: theme }] : [...themeData, { id: id, theme: theme }]))
                active = !active
                themeData = JSON.parse(localStorage.getItem('theme'))
              }}">
              save
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Select Basic -->
    <div class="field mb-5">
      <label class="label" for="complexity">Select complexity</label>
      <div class="control">
        <div class="select">
          <select id="complexity" name="complexity" bind:value="{difficulty}">
            {#each Complexity as ComplexityItem (ComplexityItem.id)}
              <option value="{ComplexityItem.value}">{ComplexityItem.name}</option>
            {/each}
          </select>
        </div>
      </div>
    </div>

    <!-- Select Basic -->
    <div class="field mb-5">
      <label class="label" for="listNumber">Select list number</label>
      <div class="control">
        <div class="select">
          <select id="listNumber" name="listNumber" bind:value="{position}">
            <option>0</option>
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>
            <option>7</option>
            <option>8</option>
          </select>
        </div>
      </div>
    </div>

    <!-- Textarea -->
    <div class="field mb-5">
      <label class="label" for="task">Enter description</label>
      <div class="control"><textarea class="textarea" id="task" name="task" bind:value="{description}" required></textarea></div>
    </div>

    <!-- File Button -->
    <label class="label" for="imageFile">Added image</label>
    <div class="file">
      <label class="file-label">
        <input
          id="imageFile"
          class="file-input"
          type="file"
          name="imageFile"
          bind:files="{image}"
          onchange="if (this.files.length > 0) document.getElementById('filename-imageFile').innerHTML = this.files[0].name; image = this.files[0]" />
        <span class="file-cta">
          <span class="file-icon"> <i class="fa fa-upload"></i> </span>
          <span class="file-label" id="filename-imageFile"> Choose a file… </span>
        </span>
      </label>
    </div>

    <!-- Prepended text
    <label class="label" for="answerOptions">Answer options</label>
    {#each fields as field, i (field.id)}
      <div class="field has-addons">
        <div class="control">
          <input id="answerOptions" name="answerOptions" class="input " placeholder="placeholder" type="text" required
                 bind:value={answerOptions[i]}>
        </div>
        {#if fields.length > 2}
          <div class="control">
            <a class="button is-danger"
               on:click|preventDefault={()=>{if (fields.length > 2) fields.splice(i, 1); fields = fields}}>
              delete
            </a>
          </div>
        {/if}
      </div>
      <p class="help mb-3">Add answer options from two or more</p>
    {/each}
    <button class="button is-primary mb-5" on:click|preventDefault={handleClick}>Add answer option</button>
     -->

    <!-- Textarea
    <div class="field">
      <label class="label" for="taskHint">Task hint</label>
      <div class="control">
        <textarea class="textarea" id="taskHint" name="solution" bind:value={taskHint}></textarea>
      </div>
    </div>
    -->

    <!-- Text input-->
    {#if autoGenerated}
      <div class="field mb-5" transition:fade="{{ duration: 250 }}">
        <label class="label" for="answer">Answer</label>
        <div class="control">
          <input id="answer" name="answer" type="text" placeholder="placeholder" class="input" bind:value="{answer}" required />
          <p class="help">Add answer</p>
        </div>
      </div>
    {/if}

    <!-- Textarea
    <div class="field mb-5">
      <label class="label" for="solution">Solution</label>
      <div class="control">
        <textarea class="textarea" id="solution" name="solution" bind:value={solution}></textarea>
      </div>
    </div>
    -->

    <!-- Button -->
    <div class="field mb-5">
      <label class="label" for="submit"></label>
      <div class="control">
        <button
          id="submit"
          name="submit"
          type="submit"
          class="button is-success"
          disabled="{disabled}">{themeData === null ? 'Add theme' : 'submit'}</button>
      </div>
    </div>
  </fieldset>
</form>

<style>
  .fieldset {
    padding: 0;
  }

  @media (min-width: 1025px) {
    .fieldset {
      padding: 0 300px 0 0;
    }
  }
</style>
